-- The firm's OWN matter reference, learned from correspondence.
--
-- case_ref_token is a reference WE generate and stamp into outgoing mail, so it only
-- helps on threads we've already touched. Every firm already has its own reference,
-- allocated by whatever case management system they run (LEAP, Osprey, Proclaim), and
-- it's written on every letter and email as "Our ref: ABC/1234" — and quoted back by
-- the other side as "Your ref: ABC/1234".
--
-- Learning it from the correspondence gives two things without integrating with
-- anything: matching on the identifier the firm actually uses, and an audit trail
-- that reconciles against their case file, because both carry the same reference.
alter table matter add column if not exists firm_ref text;

-- Matching looks this up by upper-cased value, the same way case_ref_token is used.
create index if not exists matter_firm_ref_idx on matter (tenant_id, upper(firm_ref));

comment on column matter.firm_ref is
  'The firm''s own matter reference (e.g. from LEAP), learned from "Our ref:"/"Your ref:" in correspondence. Never generated by us — see extractFirmRef in lib/server/matching.ts.';
