-- Local development only: what prod has that the migrations do not create (made on Supabase by hand
-- before the migrations existed). Run before `npm run migrate` on a fresh local database (scripts/dev-db.sh).
create table if not exists leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  first_name varchar,
  surname varchar,
  email varchar,
  firm varchar
);

-- Supabase's own roles, which some migrations grant to or revoke from.
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role nologin bypassrls; end if;
end $$;
