// Shared inline styles for the assist UI — self-contained so both the Outlook
// taskpane and the web inbox render identically regardless of the page theme.
import type * as React from 'react';

export const S: Record<string, React.CSSProperties> = {
  page: { maxWidth: 480, margin: '0 auto', padding: 12, paddingBottom: 60 },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '4px 4px 12px',
    borderBottom: '1px solid #e2e8f0',
    marginBottom: 12,
  },
  bolt: { color: '#5A27E0', fontSize: 18 },
  user: { fontSize: 12, color: '#64748b' },
  account: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    padding: 0,
  },
  planBadge: {
    fontSize: 10,
    fontWeight: 700,
    color: '#5A27E0',
    background: '#EDE7FB',
    borderRadius: 999,
    padding: '2px 7px',
  },
  iconBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    padding: 0,
  },
  subjectLine: { fontSize: 12, fontWeight: 600, color: '#475569', margin: '0 2px 8px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  hero: {
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    width: '100%',
    textAlign: 'left',
    padding: '7px 11px',
    border: '1px solid',
    borderRadius: 999,
    cursor: 'pointer',
    marginBottom: 10,
  },
  statusDot: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
    borderRadius: 999,
    color: '#fff',
    fontSize: 12,
    fontWeight: 800,
    lineHeight: 1,
    flex: 'none',
  },
  spinnerLight: {
    width: 11,
    height: 11,
    borderRadius: '50%',
    border: '2px solid rgba(255,255,255,0.45)',
    borderTopColor: '#fff',
    display: 'inline-block',
    animation: 'cl-spin 0.7s linear infinite',
  },
  heroFound: { background: '#dcfce7', borderColor: '#86efac', color: '#166534' },
  heroPartial: { background: '#fef9c3', borderColor: '#fde68a', color: '#854d0e' },
  heroNone: { background: '#fee2e2', borderColor: '#fecaca', color: '#991b1b' },
  heroPending: { background: '#f1f5f9', borderColor: '#e2e8f0', color: '#475569' },
  // When the drawer is open the pill becomes the header of a single connected
  // container: square off the bottom and drop the gap so the drawer joins onto it.
  heroOpen: { borderRadius: '14px 14px 0 0', marginBottom: 0 },
  // The drawer, rendered as the body of that container — flat top, no top border
  // (the pill's bottom edge is the divider), same coloured outline as the pill.
  matterDrawer: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderRadius: '0 0 14px 14px',
    marginTop: 0,
    marginBottom: 10,
    padding: 12,
    background: '#f8fafc',
  },
  tabBar: { display: 'flex', gap: 2, marginBottom: 12, borderBottom: '1px solid #e2e8f0' },
  tabBtn: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, padding: '8px 6px', background: 'transparent', border: 'none', borderBottom: '2px solid transparent', marginBottom: -1, fontSize: 12, fontWeight: 600, color: '#64748b', cursor: 'pointer' },
  tabBtnActive: { color: '#5A27E0', borderBottomColor: '#5A27E0' },
  tabBtnLocked: { opacity: 0.4, cursor: 'not-allowed' },
  fileList: { border: '1px solid #e2e8f0', borderRadius: 8, overflow: 'hidden', background: '#fff', marginTop: 4 },
  fileRow: { display: 'flex', alignItems: 'center', gap: 8, padding: '7px 9px', borderBottom: '1px solid #f1f5f9', textDecoration: 'none', color: '#0f172a', cursor: 'pointer' },
  fileExt: { flex: 'none', width: 38, textAlign: 'center', fontSize: 9, fontWeight: 700, letterSpacing: 0.3, color: '#5A27E0', background: '#EDE7FB', borderRadius: 4, padding: '3px 0' },
  fileName: { flex: 1, minWidth: 0, fontSize: 13, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  fileMeta: { flex: 'none', fontSize: 11, color: '#94a3b8' },
  fileBtn: { flex: 'none', padding: '3px 9px', background: '#5A27E0', color: '#fff', border: 'none', borderRadius: 6, fontSize: 11, fontWeight: 700, cursor: 'pointer' },
  fileDone: { flex: 'none', fontSize: 10, fontWeight: 700, color: '#166534', background: '#dcfce7', borderRadius: 999, padding: '2px 7px' },
  iconAction: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 30, height: 30, border: '1px solid #cbd5e1', borderRadius: 7, background: '#fff', color: '#475569', cursor: 'pointer', textDecoration: 'none' },
  acctRow: { display: 'flex', alignItems: 'center', gap: 10, width: '100%', textAlign: 'left', fontSize: 13, fontWeight: 600, color: '#334155', background: '#fff', border: '1px solid #eef2f7', borderRadius: 10, padding: '10px 12px', marginTop: 8, cursor: 'pointer', fontFamily: 'inherit' },
  fileIcon: { flex: 'none', display: 'inline-flex', color: '#94a3b8' },
  actionRow: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 6, marginBottom: 4 },
  actionBtn: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 3,
    padding: '8px 4px',
    background: '#fff',
    border: '1px solid #cbd5e1',
    borderRadius: 8,
    fontSize: 11,
    fontWeight: 600,
    color: '#334155',
    cursor: 'pointer',
  },
  actionBtnActive: { background: '#5A27E0', borderColor: '#5A27E0', color: '#fff' },
  recDot: { position: 'absolute', top: 5, right: 5, width: 6, height: 6, borderRadius: 999, background: '#22c55e' },
  actionPanel: { marginTop: 8, padding: 10, background: '#fff', border: '1px solid #e2e8f0', borderRadius: 8 },
  updateLabel: { display: 'block', fontSize: 11, color: '#64748b', marginBottom: 6 },
  updateChip: { display: 'inline-flex', alignItems: 'center', gap: 6, padding: '5px 10px', background: '#f5f3ff', border: '1px solid #ddd6fe', borderRadius: 999, fontSize: 12, color: '#5A27E0', cursor: 'pointer', fontWeight: 600 },
  updateChipRole: { fontSize: 10, fontWeight: 500, color: '#7c6fb0', background: '#fff', border: '1px solid #e9e4ff', borderRadius: 999, padding: '1px 6px' },
  previewBody: { marginTop: 8, padding: 10, background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: 8, fontSize: 12, lineHeight: 1.5, color: '#0f172a', maxHeight: 240, overflow: 'auto' },
  spinner: {
    width: 12,
    height: 12,
    borderRadius: '50%',
    border: '2px solid #cbd5e1',
    borderTopColor: '#5A27E0',
    display: 'inline-block',
    animation: 'cl-spin 0.7s linear infinite',
  },
  assistIcon: {
    width: 20,
    height: 20,
    borderRadius: 6,
    background: '#5A27E0',
    color: '#fff',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    flex: 'none',
  },
  card: {
    border: '1px solid #e2e8f0',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    background: '#f8fafc',
  },
  label: { fontWeight: 700, fontSize: 13, marginBottom: 8, color: '#0f172a' },
  sectionHead: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    background: 'transparent',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
  },
  sectionCount: {
    display: 'inline-block',
    marginLeft: 7,
    fontSize: 11,
    fontWeight: 700,
    color: '#5A27E0',
    background: '#EDE7FB',
    borderRadius: 999,
    padding: '1px 7px',
  },
  subLabel: { fontWeight: 600, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.4, color: '#64748b', margin: '10px 0 4px' },
  fieldLabel: { display: 'block', fontSize: 11, color: '#64748b', marginBottom: 2 },
  linkedMatter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    background: '#f1edfd',
    border: '1px solid #ddd6fe',
    borderRadius: 8,
    padding: '7px 10px',
    fontSize: 13,
    fontWeight: 600,
    color: '#4A1FBE',
    marginBottom: 8,
  },
  tagBox: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 4,
    alignItems: 'center',
    border: '1px solid #cbd5e1',
    borderRadius: 6,
    padding: 4,
    minHeight: 38,
    background: '#fff',
    marginBottom: 6,
  },
  tag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    background: '#ede9fb',
    color: '#4A1FBE',
    borderRadius: 999,
    padding: '2px 4px 2px 9px',
    fontSize: 12,
    fontWeight: 600,
  },
  tagX: { border: 'none', background: 'transparent', cursor: 'pointer', fontSize: 15, lineHeight: 1, color: '#7c6bb0', padding: '0 3px' },
  tagInput: { flex: 1, minWidth: 90, border: 'none', outline: 'none', padding: '4px 6px', fontSize: 13, background: 'transparent' },
  muted: { fontSize: 12, color: '#64748b', margin: '0 0 10px' },
  threadSubject: { fontSize: 13, fontWeight: 600, marginBottom: 10, color: '#0f172a' },
  rowWrap: { display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 6 },
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 },
  input: {
    width: '100%',
    padding: '7px 9px',
    border: '1px solid #cbd5e1',
    borderRadius: 6,
    fontSize: 13,
    marginBottom: 6,
  },
  textarea: {
    width: '100%',
    padding: '8px 9px',
    border: '1px solid #cbd5e1',
    borderRadius: 6,
    fontSize: 13,
    fontFamily: 'inherit',
    resize: 'vertical',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15,23,42,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    zIndex: 50,
  },
  modalCard: {
    position: 'relative',
    width: '100%',
    maxWidth: 360,
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: 14,
    padding: 18,
    boxShadow: '0 20px 50px -20px rgba(15,23,42,0.5)',
  },
  copyBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    marginTop: 14,
    padding: '10px 12px',
    background: '#f5f3ff',
    border: '1px solid #ddd6fe',
    borderRadius: 9,
    cursor: 'pointer',
    textAlign: 'left',
    fontFamily: 'inherit',
  },
  copyBoxText: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: 12,
    color: '#5b21b6',
    fontWeight: 600,
  },
  scrollList: {
    maxHeight: 240,
    overflowY: 'auto',
    border: '1px solid #e2e8f0',
    borderRadius: 8,
    background: '#fff',
  },
  scrollRow: {
    padding: '7px 10px',
    borderBottom: '1px solid #f1f5f9',
    fontSize: 12,
    color: '#334155',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  primary: {
    width: '100%',
    padding: '9px 12px',
    background: '#5A27E0',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontWeight: 700,
    fontSize: 13,
    cursor: 'pointer',
    marginTop: 4,
  },
  secondary: {
    padding: '7px 10px',
    background: '#fff',
    color: '#0f172a',
    border: '1px solid #cbd5e1',
    borderRadius: 6,
    fontSize: 12,
    cursor: 'pointer',
  },
  action: {
    padding: '10px',
    background: '#0f172a',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  tone: { padding: '5px 10px', background: '#fff', border: '1px solid #cbd5e1', borderRadius: 6, fontSize: 12, cursor: 'pointer' },
  toneActive: { padding: '5px 10px', background: '#5A27E0', border: '1px solid #5A27E0', borderRadius: 6, fontSize: 12, cursor: 'pointer', fontWeight: 700 },
  ul: { margin: '0 0 4px', paddingLeft: 18, fontSize: 13, lineHeight: 1.5 },
  chip: { fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 999, background: '#e2e8f0', color: '#0f172a', textTransform: 'uppercase', letterSpacing: 0.3 },
  candidate: { border: '1px solid #e2e8f0', borderRadius: 8, padding: 8, marginBottom: 6, background: '#fff' },
  confidence: { fontSize: 11, fontWeight: 700, padding: '2px 8px', borderRadius: 6, color: '#0f172a' },
  kv: { display: 'flex', justifyContent: 'space-between', fontSize: 12, padding: '3px 0', color: '#334155', gap: 12 },
  trk: { width: '100%', borderCollapse: 'collapse', fontSize: 12, border: '1px solid #e2e8f0', borderRadius: 8, overflow: 'hidden', background: '#fff' },
  trkH: { textAlign: 'left', fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.4, color: '#64748b', padding: '6px 8px', borderBottom: '1px solid #e2e8f0', background: '#f8fafc' },
  trkC: { fontSize: 12, color: '#0f172a', padding: '6px 8px', borderBottom: '1px solid #f1f5f9', verticalAlign: 'top' },
  pillBtn: { display: 'inline-flex', alignItems: 'center', gap: 4, padding: '5px 10px', background: '#5A27E0', color: '#fff', border: 'none', borderRadius: 7, fontSize: 11, fontWeight: 700, cursor: 'pointer', textDecoration: 'none' },
  // Light, tidy board links (Team tracker / Case log) — equal width when stacked.
  boardBtn: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5, padding: '5px 12px', background: '#f5f3ff', color: '#5A27E0', border: '1px solid #ddd6fe', borderRadius: 8, fontSize: 11, fontWeight: 700, cursor: 'pointer', textDecoration: 'none', whiteSpace: 'nowrap' },
  // Quick-action buttons (Delegate / Notify) — white on purple.
  quickAct: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, padding: '8px 10px', background: '#5A27E0', color: '#fff', border: 'none', borderRadius: 7, fontSize: 13, fontWeight: 700, cursor: 'pointer' },
  // Borderless icon button (e.g. the status refresh) — no boxy outline.
  ghostIcon: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 22, height: 22, padding: 0, background: 'transparent', border: 'none', color: '#94a3b8', cursor: 'pointer', borderRadius: 6 },
  kvRow: { display: 'flex', gap: 8, fontSize: 12, padding: '3px 0', alignItems: 'baseline' },
  kvKey: { flex: 'none', width: 74, color: '#64748b', fontWeight: 600, whiteSpace: 'nowrap' },
  kvVal: { flex: 1, minWidth: 0, color: '#0f172a', lineHeight: 1.45, wordBreak: 'break-word' },
  link: { display: 'block', fontSize: 12, color: '#5A27E0', margin: '6px 0', textDecoration: 'none', fontWeight: 600 },
  toast: {
    position: 'fixed',
    left: 12,
    right: 12,
    bottom: 28,
    maxWidth: 456,
    margin: '0 auto',
    background: '#0f172a',
    color: '#fff',
    padding: '10px 12px',
    borderRadius: 8,
    fontSize: 12,
    boxShadow: '0 6px 20px rgba(0,0,0,0.25)',
  },
  toastBusy: { background: '#5A27E0' },
  schedWrap: {
    position: 'fixed',
    left: 12,
    right: 12,
    bottom: 76,
    maxWidth: 456,
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    zIndex: 5,
  },
  schedChip: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: '#fffbeb',
    border: '1px solid #fde68a',
    color: '#92400e',
    padding: '8px 10px',
    borderRadius: 10,
    fontSize: 12.5,
    boxShadow: '0 6px 20px rgba(0,0,0,0.12)',
  },
  schedCancel: {
    flex: 'none',
    background: '#fff',
    border: '1px solid #d97706',
    color: '#b45309',
    fontWeight: 700,
    fontSize: 12,
    padding: '4px 10px',
    borderRadius: 8,
    cursor: 'pointer',
  },
};
