import crypto from 'node:crypto';
import { NextRequest } from 'next/server';
import { assertFeature } from '@/lib/server/config';
import { ok, fail } from '@/lib/server/http';
import { queryOne, runAsAutomation, runAsSystem } from '@/lib/server/db';
import { toWebhookEvent } from '@/lib/server/integrations/intouch/mapping';
import { applyWebhook } from '@/lib/server/integrations/intouch/sync';
import { inTouchSyncDeps, inTouchWebhookKey } from '@/lib/server/integrations/intouch/adapters';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 120;

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * InTouch → CONVEYi.
 *
 * The firm adds this URL in InTouch (Settings > API > Webhooks) — there is no API to
 * subscribe. InTouch does not sign deliveries, so the URL itself carries the proof:
 * `firm` says whose it is and `key` (generated by us, kept encrypted) must match, compared
 * in constant time. Nothing is read or acted on before that.
 *
 * The body is a POINTER (event name, who triggered it), never trusted for content: the
 * handler re-reads the case from InTouch. Runs as automation, so nothing arriving this way
 * can write a payment or a send event whatever it claims to be.
 *
 * Once authenticated the answer is 2xx — even for an event we skip — because InTouch
 * retries anything else (+10m, +60m, +180m, +24h) and a skip will not change. A sync that
 * THROWS returns 500, so InTouch's retry schedule re-delivers it.
 */
export async function POST(req: NextRequest) {
  try {
    assertFeature('db');
    const tenantId = req.nextUrl.searchParams.get('firm') ?? '';
    const key = req.nextUrl.searchParams.get('key') ?? '';
    if (!UUID.test(tenantId) || !key) return unauthorised();
    const expected = await inTouchWebhookKey(tenantId);
    if (!expected || !sameKey(key, expected)) return unauthorised();

    const raw = await req.text();
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return ok({ received: true, outcome: { status: 'IGNORED', reason: 'body is not JSON' } });
    }
    const connected = await runAsSystem(() => queryOne<{ status: string }>(`select status from intouch_connection where tenant_id = $1`, [tenantId])).catch(() => null);
    if (connected?.status !== 'CONNECTED') return ok({ received: true, outcome: { status: 'IGNORED', reason: 'InTouch is not connected for this firm' } });

    const event = toWebhookEvent(parsed, raw);
    try {
      const deps = await inTouchSyncDeps(tenantId);
      const summary = await runAsAutomation(() => applyWebhook(deps, tenantId, event));
      return ok({ received: true, event: event.type, summary });
    } catch (err) {
      console.warn('[intouch] webhook failed', event.type, err instanceof Error ? err.message : err);
      return fail(Object.assign(new Error('The InTouch event could not be applied; InTouch will retry.'), { status: 500 }));
    }
  } catch (error) {
    return fail(error);
  }
}

function unauthorised() {
  return fail(Object.assign(new Error('Unknown firm or webhook key.'), { status: 401 }));
}

/** Constant-time, and length-blind: compare digests, not the strings. */
function sameKey(given: string, expected: string): boolean {
  const a = crypto.createHash('sha256').update(given, 'utf8').digest();
  const b = crypto.createHash('sha256').update(expected, 'utf8').digest();
  return crypto.timingSafeEqual(a, b);
}
