/**
 * Render the state machine to a Markdown + Mermaid document, procedurally, from the same
 * `machineSpec()` the read-only map page and the consistency tests use. Nothing here is
 * hand-written: change the machine, re-run `npm run engine:map`, commit the diff.
 *
 *   npm run engine:map            → docs/engine-map.md
 *   npm run engine:map -- --json  → docs/engine-map.json
 */
import fs from 'node:fs';
import path from 'node:path';
import { machineSpec } from '../lib/server/engine/spec';
import { LIFECYCLE, LIFECYCLE_LABEL, WORKSTREAM_LABEL } from '../lib/server/engine/graph';
import { ISSUE_KIND_SPECS, ISSUE_GROUP_LABEL, WORKSTREAMS } from '../lib/server/engine/issues';
import { CLIENT_DECISION_OUTCOMES } from '../lib/server/engine/types';

const spec = machineSpec();
const json = process.argv.includes('--json');
const out = path.join(process.cwd(), 'docs', json ? 'engine-map.json' : 'engine-map.md');

if (json) {
  fs.writeFileSync(out, JSON.stringify(spec, null, 2));
  console.log(`wrote ${out} (spec ${spec.version})`);
  process.exit(0);
}

const esc = (s: string) => s.replace(/"/g, "'").replace(/\|/g, '/');
const L: string[] = [];
L.push(`# The conveyancing state machine, generated from code`);
L.push('');
L.push(`> Generated by \`npm run engine:map\` from \`lib/server/engine/spec.ts\` (\`machineSpec()\`), the same source the live map at \`/engine/map\` draws and \`tests/unit/engine/spec.test.ts\` checks against the machine. **Do not edit by hand** — change the machine and re-run. Spec version \`${spec.version}\`.`);
L.push('');
L.push(`${spec.stages.length} stages · ${spec.subflows.length} sub-flows · ${spec.commands.length} commands · ${spec.events.length} event types · ${spec.decisions.length} decision kinds · ${spec.triggers.length} triggers · ${spec.eventualities.length} eventualities · ${spec.issues.kinds.length} issue kinds · ${WORKSTREAMS.length} workstreams.`);
L.push('');

// 0 · lifecycle over phases
L.push('## 0 · Case lifecycle (coarse) over the engine\'s phases');
L.push('');
L.push('```mermaid');
L.push('stateDiagram-v2');
L.push('    direction LR');
L.push('    [*] --> instructed');
L.push('    state pre_exchange {');
L.push('        direction LR');
L.push('        pre_contract --> contract_review');
L.push('        contract_review --> pre_exchange_phase');
L.push('        pre_exchange_phase: pre_exchange (phase)');
L.push('    }');
L.push('    instructed --> pre_exchange');
L.push('    pre_exchange --> ready_to_exchange: every exchange requirement satisfied (derived)');
L.push('    ready_to_exchange --> exchanged: contracts_exchanged');
L.push('    exchanged --> pre_completion: completion_statement_generated');
L.push('    pre_completion --> completed: completion_confirmed');
L.push('    completed --> post_completion: sdlt_submitted / ap1_submitted');
L.push('    post_completion --> closed: ap1_confirmed then close_matter');
L.push('    closed --> [*]');
L.push('    instructed --> aborted: abandon_matter / mark_issue_fatal');
L.push('    pre_exchange --> aborted');
L.push('    ready_to_exchange --> aborted');
L.push('    aborted --> [*]');
L.push('```');
L.push('');
L.push(`Lifecycle states: ${LIFECYCLE.map((l) => `\`${l}\` (${LIFECYCLE_LABEL[l]})`).join(' → ')}, plus \`aborted\`.`);
L.push('');

// 1 · stage spine with gates
L.push('## 1 · The stage spine and its gates');
L.push('');
L.push('```mermaid');
L.push('flowchart LR');
spec.stages.forEach((s, i) => {
  L.push(`    ${s.id}["${esc(s.label)}"]`);
  if (i > 0) L.push(`    ${spec.stages[i - 1].id} -->|"${esc(spec.stages[i - 1].gates.join(' · '))}"| ${s.id}`);
});
spec.terminal.forEach((t) => L.push(`    ${t.id}(["${esc(t.label)}"])`));
L.push(`    ${spec.stages[spec.stages.length - 1].id} --> registered`);
L.push('    instruction -.-> abandoned');
L.push('    pre_exchange -.-> abandoned');
L.push('    registered --> closed');
L.push('```');
L.push('');
L.push('| Stage | Purpose | Gates to leave | Sub-flows | Typical commands |');
L.push('| --- | --- | --- | --- | --- |');
for (const s of spec.stages) L.push(`| \`${s.id}\` | ${esc(s.purpose)} | ${s.gates.map(esc).join('; ')} | ${s.subflows.join(', ') || '—'} | ${s.typical.map((c) => `\`${c}\``).join(', ')} |`);
L.push('');

// 2 · sub-flows
L.push('## 2 · Sub-flows (the event pair pattern, once per sub-flow)');
L.push('');
L.push('```mermaid');
L.push('flowchart LR');
for (const sf of spec.subflows) {
  L.push(`    subgraph ${sf.id}["${esc(sf.label)} · ${sf.stage}${sf.waitKey ? ` · wait: ${sf.waitKey}` : ''}"]`);
  L.push('        direction LR');
  const start = sf.start[sf.start.length - 1];
  L.push(`        ${sf.id}_s["${start}"]`);
  if (sf.extracted && sf.extracted !== start) { L.push(`        ${sf.id}_x["${sf.extracted}"]`); L.push(`        ${sf.id}_s --> ${sf.id}_x`); }
  const from = sf.extracted && sf.extracted !== start ? `${sf.id}_x` : `${sf.id}_s`;
  if (sf.cleared) { L.push(`        ${sf.id}_c["${sf.cleared}"]`); L.push(`        ${from} -->|rule: clear| ${sf.id}_c`); }
  if (sf.flagged) { L.push(`        ${sf.id}_f["${sf.flagged}"]`); L.push(`        ${from} -->|${sf.cleared ? 'rule: flag' : 'always a decision'}| ${sf.id}_f`); }
  if (sf.reviewed && sf.flagged) { L.push(`        ${sf.id}_r["${sf.reviewed}"]`); L.push(`        ${sf.id}_f -->|person| ${sf.id}_r`); }
  L.push('    end');
}
L.push('```');
L.push('');
L.push('| Sub-flow | Rule (deterministic, never the AI) | Decision options |');
L.push('| --- | --- | --- |');
for (const sf of spec.subflows) L.push(`| **${esc(sf.label)}** | ${esc(sf.rule)} | ${sf.decisionKind ? spec.decisions.find((d) => d.kind === sf.decisionKind)?.options.join(' · ') ?? '' : '—'} |`);
L.push('');

// 3 · workstreams
L.push('## 3 · Workstreams (the concurrent lanes the case model projects)');
L.push('');
L.push(WORKSTREAMS.map((w) => `\`${w}\` (${WORKSTREAM_LABEL[w]})`).join(' · '));
L.push('');
L.push('Each lane reads not started / in progress / awaiting / under review / blocked / at risk / complete from the engine state (`lib/server/engine/graph.ts → workstreams()`); the exchange, completion, registration and close gates list their requirements with the authority that satisfies each (`requirements()`).');
L.push('');

// 4 · commands
L.push('## 4 · Commands: who may record what, and when');
L.push('');
L.push('| Command | Actor | Stages | Emits | Description |');
L.push('| --- | --- | --- | --- | --- |');
for (const c of spec.commands) L.push(`| \`${c.type}\`${c.humanGated ? ' 🔒' : ''}${c.hardStop ? ' ⛔' : ''} | ${c.actor} | ${c.stages === 'any' ? 'any' : c.stages === 'not_enrolled' ? 'not enrolled' : c.stages.join(', ')} | ${c.emits.map((e) => `\`${e}\``).join(' ')} | ${esc(c.description)} |`);
L.push('');
L.push('🔒 human-gated at the database (automation cannot write it). ⛔ hard stop while a bank-details decision is pending.');
L.push('');

// 5 · events
L.push('## 5 · Event types');
L.push('');
const cats = Array.from(new Set(spec.events.map((e) => e.category)));
for (const c of cats) L.push(`- **${c}**: ${spec.events.filter((e) => e.category === c).map((e) => `\`${e.type}\`${e.decision ? ' (decision)' : ''}${e.humanGated ? ' 🔒' : ''}`).join(', ')}`);
L.push('');

// 6 · time
L.push('## 6 · Time as a trigger');
L.push('');
L.push('| Wait | Chase after | Then every | Escalate after | Re-escalate after | Recipient |');
L.push('| --- | --- | --- | --- | --- | --- |');
for (const w of spec.timers.waits) L.push(`| \`${w.waitKey}\` | ${w.chaseAfter} wd | ${w.chaseEvery ?? '—'}${w.chaseEvery ? ' wd' : ''} | ${w.escalateAfter} wd | ${w.reEscalateAfter} wd | ${w.recipientRole} |`);
L.push('');
L.push('| Deadline | Raised | About |');
L.push('| --- | --- | --- |');
for (const d of spec.timers.deadlines) L.push(`| \`${d.kind}\` | ${d.leadWorkingDays} working days ${d.kind === 'stale_issue' ? 'without movement' : 'before'} | ${esc(d.description)} |`);
L.push('');
L.push('Timed issues (`sla.ts → timedIssueActions`): mortgage offer VALID → EXPIRING (30 days, warning) → CRITICAL (14 days) → EXPIRED (offer withdrawn, critical issue); a search / enquiry past its escalation point becomes an informational issue the timer also closes; an open issue past its kind\'s escalation period goes up a severity.');
L.push('');

// 7 · issues
L.push('## 7 · Issues: what goes wrong, what it holds, the ways out');
L.push('');
L.push('```mermaid');
L.push('stateDiagram-v2');
L.push('    direction LR');
L.push('    [*] --> open: raise_issue (person / rules / timer)');
L.push('    open --> negotiating: update_issue');
L.push('    negotiating --> open');
L.push('    open --> resolved: resolve_issue (kind-specific outcome)');
L.push('    negotiating --> resolved');
L.push('    open --> withdrawn: withdraw_issue (reason)');
L.push('    negotiating --> withdrawn');
L.push('    open --> fatal: mark_issue_fatal → matter_abandoned');
L.push('    negotiating --> fatal');
L.push('    resolved --> [*]');
L.push('    withdrawn --> [*]');
L.push('    fatal --> [*]');
L.push('```');
L.push('');
L.push('| Kind | Group | Holds | Severity | Workstreams | Threatens | Owner | Escalates after | Resolutions |');
L.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |');
for (const k of ISSUE_KIND_SPECS) L.push(`| **${esc(k.label)}** \`${k.kind}\` | ${ISSUE_GROUP_LABEL[k.group]} | ${k.gate} | ${k.severity} | ${k.workstreams.join(', ') || '—'} | ${k.threatens.join(', ')} | ${k.responsible} | ${k.escalateAfterWorkingDays ?? '—'}${k.escalateAfterWorkingDays ? ' wd' : ''} | ${k.resolutions.join(', ')} |`);
L.push('');
L.push('| Resolution | Effect on the rest of the machine |');
L.push('| --- | --- |');
for (const r of spec.issues.resolutions.filter((x) => x.effects.length)) L.push(`| \`${r.id}\` | ${r.effects.join('; ')} |`);
L.push('');

// 8 · client decisions + authority
L.push('## 8 · Client decisions (recorded by a person, never inferred)');
L.push('');
for (const [subject, outcomes] of Object.entries(CLIENT_DECISION_OUTCOMES)) L.push(`- \`${subject}\`: ${outcomes.join(' / ')}`);
L.push('');

// 9 · decisions
L.push('## 9 · Decision kinds');
L.push('');
L.push('| Kind | Options | Source the person must open |');
L.push('| --- | --- | --- |');
for (const d of spec.decisions) L.push(`| \`${d.kind}\` | ${d.options.join(' · ')} | ${esc(d.source)} |`);
L.push('');

// 10 · triggers
L.push('## 10 · Triggers: every door into the engine');
L.push('');
L.push('| Trigger | Backend | Source | Feeds | Reaches | Built |');
L.push('| --- | --- | --- | --- | --- | --- |');
for (const t of spec.triggers) L.push(`| ${esc(t.label)} | ${t.backend} | ${t.source} | ${t.feeds} | ${t.reaches.join(', ') || '—'} | ${t.implemented ? 'yes' : 'planned'} |`);
L.push('');

// 11 · invariants
L.push('## 11 · Invariants the machine enforces');
L.push('');
for (const v of spec.invariants) L.push(`- **${esc(v.title)}** — ${esc(v.rule)} _(${v.enforcedBy.join(', ')})_`);
L.push('');

// 12 · eventualities
L.push('## 12 · Eventualities');
L.push('');
L.push('| Area | Scenario | Handling | Mechanism |');
L.push('| --- | --- | --- | --- |');
for (const e of spec.eventualities) L.push(`| ${e.area} | ${esc(e.scenario)} | ${e.handling} | ${esc(e.mechanism)} |`);
L.push('');
L.push(`_${spec.generatedFrom}_`);
fs.writeFileSync(out, L.join('\n'));
console.log(`wrote ${out} (spec ${spec.version}, ${L.length} lines)`);
