/**
 * Component #5 — message templates. Two families, deliberately separate:
 *
 *   CLIENT_UPDATES — status updates to the buyer. Pure admin, zero legal content:
 *                    "your search is back", "we're waiting on X". Safe to send
 *                    automatically. They never contain transaction-specific advice.
 *   CHASES         — template chase messages to third parties (seller's solicitor,
 *                    search provider, lender, HMLR, the client for ID documents),
 *                    fired by the engine's timers. Template-based, not AI-written.
 *
 * Rendering is deterministic: `{{var}}` placeholders, missing values render as
 * empty and are reported so a caller can refuse to send a half-filled message.
 */
export interface Template {
  key: string;
  channel: 'client' | 'chase';
  subject: string;
  body: string;
  /** Variables the body needs; render() reports which are missing. */
  requires: string[];
}

const T = (key: string, channel: Template['channel'], subject: string, body: string, requires: string[] = []): Template => ({ key, channel, subject, body, requires });

export const CLIENT_UPDATES: Record<string, Template> = {
  searches_ordered: T('searches_ordered', 'client', 'Your {{transaction}} of {{property}} — searches ordered', 'Hello {{firstName}},\n\nA quick update on {{property}}: we have ordered the property searches ({{searchList}}). These usually take two to three weeks to come back from the local authority and other providers. We will let you know when they are all back.\n\nNothing is needed from you right now.\n\n{{feeEarner}}\n{{firmName}}'),
  searches_all_back: T('searches_all_back', 'client', 'Your {{transaction}} of {{property}} — searches all back', 'Hello {{firstName}},\n\nAll the searches on {{property}} are back ({{searchList}}) and your conveyancer has been through each of them. We will set out what they show in your report on title.\n\n{{feeEarner}}\n{{firmName}}'),
  search_back_all_clear: T('search_back_all_clear', 'client', 'Your {{transaction}} of {{property}} — search received', 'Hello {{firstName}},\n\nThe {{searchName}} for {{property}} has come back and nothing in it needs any action. We will include a summary in your report on title.\n\n{{feeEarner}}\n{{firmName}}'),
  search_back_under_review: T('search_back_under_review', 'client', 'Your {{transaction}} of {{property}} — search received', 'Hello {{firstName}},\n\nThe {{searchName}} for {{property}} has come back and your conveyancer is reviewing one or two entries in it. That is normal — most searches have something to check. We will be in touch if anything needs your input.\n\n{{feeEarner}}\n{{firmName}}'),
  enquiries_raised: T('enquiries_raised', 'client', 'Your purchase of {{property}} — we have asked the seller\'s side', 'Hello {{firstName}},\n\n{{enquiryLine}}\n\n{{feeEarner}}\n{{firmName}}', ['enquiryLine']),
  mortgage_offer_checked: T('mortgage_offer_checked', 'client', 'Your {{transaction}} of {{property}} — mortgage offer checked', 'Hello {{firstName}},\n\nWe have received and checked your mortgage offer for {{property}}. Its conditions are in order for us to proceed.\n\n{{feeEarner}}\n{{firmName}}'),
  report_on_title_sent: T('report_on_title_sent', 'client', 'Your purchase of {{property}} — report on title', 'Hello {{firstName}},\n\nYour report on title for {{property}} has been sent to you separately. Please read it carefully and come back to us with any questions before we exchange contracts.\n\n{{feeEarner}}\n{{firmName}}'),
  exchanged: T('exchanged', 'client', 'Your purchase of {{property}} — contracts exchanged', 'Hello {{firstName}},\n\nGood news: contracts have been exchanged on {{property}}. The purchase is now legally binding and completion is set for {{completionDate}}.\n\n{{feeEarner}}\n{{firmName}}'),
  completed: T('completed', 'client', 'Your purchase of {{property}} — completed', 'Hello {{firstName}},\n\nCongratulations — your purchase of {{property}} has completed today. Keys are released through the estate agent. We will now deal with the stamp duty return and the Land Registry registration.\n\n{{feeEarner}}\n{{firmName}}'),
  registration_complete: T('registration_complete', 'client', 'Your purchase of {{property}} — registered', 'Hello {{firstName}},\n\nHM Land Registry has now registered you as the owner of {{property}}. We will send you the updated title information for your records. This concludes the legal work on your purchase.\n\n{{feeEarner}}\n{{firmName}}'),
  property_forms_request: T('property_forms_request', 'client', 'Your sale of {{property}}: the property forms', 'Hello {{firstName}},\n\nTo prepare the contract for your sale of {{property}} we need you to complete the Property Information Form (TA6) and the Fittings and Contents Form (TA10){{leaseholdForms}}. Answer as fully as you can; \"not known\" is fine where you genuinely do not know.\n\nPlease also send us copies of any planning permissions, building regulations certificates, guarantees and warranties, and the boiler service records.\n\n{{feeEarner}}\n{{firmName}}'),
  ownership_basis_request: T('ownership_basis_request', 'client', 'Your purchase of {{property}}: how you will own it', 'Hello {{firstName}},\n\nAs you are buying {{property}} together, we need to know how you want to own it:\n\n• Joint tenants: you own the whole property together. If one of you dies, the other automatically owns it all, whatever a will says.\n• Tenants in common: you each own a share (equal or unequal), which passes under your will. If your contributions differ, this is usually the way to protect them, with a declaration of trust recording the shares.\n\nPlease reply to tell us which you choose (and the shares, for tenants in common). If your interests differ, or you would like to talk it through, each of you can speak to us separately before deciding.\n\n{{feeEarner}}\n{{firmName}}'),
  exchange_authority_request: T('exchange_authority_request', 'client', 'Your purchase of {{property}}: your authority to exchange', 'Hello {{firstName}},\n\nWe are close to exchanging contracts for {{property}}. Once contracts are exchanged you are legally bound to buy, and the deposit is at risk if you do not complete.\n\nPlease reply to confirm that you have read our report on title, that you are happy to go ahead, and that we have your authority to exchange contracts{{completionLine}}.\n\n{{feeEarner}}\n{{firmName}}'),
  buildings_insurance_request: T('buildings_insurance_request', 'client', 'Your purchase of {{property}}: buildings insurance', 'Hello {{firstName}},\n\nContracts are exchanged, so {{property}} is now your risk: your lender requires buildings insurance to be in place from today (it must be, before we can complete).\n\nPlease arrange it if you have not already, and send us a copy of the policy schedule showing the insurer, the start date and your lender noted as mortgagee.\n\n{{feeEarner}}\n{{firmName}}'),
  balance_request: T('balance_request', 'client', 'Your purchase of {{property}}: the balance for completion', 'Hello {{firstName}},\n\nCompletion of {{property}} is set for {{completionDate}}. The completion statement we sent shows the balance we need from you; please make sure it reaches our client account as cleared funds at least two working days before completion.\n\nWe will give you our bank details by phone. Never send money to bank details you receive by email, even if the email appears to come from us: always check them with us by phone first.\n\n{{feeEarner}}\n{{firmName}}'),
  // ── The same news for other kinds of case: chosen by forTransaction (key__sale, key__remortgage, key__transfer). ──
  searches_all_back__remortgage: T('searches_all_back__remortgage', 'client', 'Your remortgage of {{property}} — searches all back', 'Hello {{firstName}},\n\nAll the searches on {{property}} are back ({{searchList}}) and your conveyancer has been through each of them. Nothing in them holds up your remortgage; anything your new lender needs to know, we tell them.\n\n{{feeEarner}}\n{{firmName}}'),
  mortgage_offer_checked__remortgage: T('mortgage_offer_checked__remortgage', 'client', 'Your remortgage of {{property}} — new mortgage offer checked', 'Hello {{firstName}},\n\nWe have received and checked your new mortgage offer for {{property}}. Its conditions are in order. Next, we send you the mortgage deed to sign, and ask your current lender for the figure to pay them off on completion.\n\n{{feeEarner}}\n{{firmName}}'),
  exchanged__sale: T('exchanged__sale', 'client', 'Your sale of {{property}} — contracts exchanged', 'Hello {{firstName}},\n\nGood news: contracts have been exchanged on {{property}}. The sale is now legally binding and completion is set for {{completionDate}}.\n\nBefore then:\n• Arrange your move so the property is empty by 1pm on completion day, with everything the contract includes left behind.\n• Leave every set of keys with the estate agent; they release them once we confirm the buyer\'s money is in.\n• Take meter readings on the day and give them to your suppliers.\n\nOn completion we pay off your mortgage from the sale money and send you the balance, with a statement.\n\n{{feeEarner}}\n{{firmName}}'),
  completed__sale: T('completed__sale', 'client', 'Your sale of {{property}} — completed', 'Hello {{firstName}},\n\nYour sale of {{property}} has completed today: the buyer\'s money is in and the estate agent can release the keys. We are paying off your mortgage from the proceeds and will send you the balance, with a completion statement showing every figure.\n\n{{feeEarner}}\n{{firmName}}'),
  completed__remortgage: T('completed__remortgage', 'client', 'Your remortgage of {{property}} — completed', 'Hello {{firstName}},\n\nYour remortgage of {{property}} has completed today: your new lender\'s money is in and we have paid off your previous mortgage. We will now register the new charge at HM Land Registry and have the old one removed, and send you a completion statement.\n\n{{feeEarner}}\n{{firmName}}'),
  completed__transfer: T('completed__transfer', 'client', 'Your transfer of equity of {{property}} — completed', 'Hello {{firstName}},\n\nThe transfer of {{property}} has completed today. We will now file any stamp duty return due and register the change of ownership at HM Land Registry, and let you know when it is done.\n\n{{feeEarner}}\n{{firmName}}'),
  registration_complete__remortgage: T('registration_complete__remortgage', 'client', 'Your remortgage of {{property}} — registered', 'Hello {{firstName}},\n\nHM Land Registry has now registered your new lender\'s charge on {{property}} and removed the old one. This concludes the legal work on your remortgage.\n\n{{feeEarner}}\n{{firmName}}'),
  registration_complete__transfer: T('registration_complete__transfer', 'client', 'Your transfer of equity of {{property}} — registered', 'Hello {{firstName}},\n\nHM Land Registry has now registered the new ownership of {{property}}. We will send you the updated title for your records. This concludes the legal work on the transfer.\n\n{{feeEarner}}\n{{firmName}}'),
  exchange_authority_request__sale: T('exchange_authority_request__sale', 'client', 'Your sale of {{property}}: your authority to exchange', 'Hello {{firstName}},\n\nWe are close to exchanging contracts on your sale of {{property}}. Once contracts are exchanged you are legally bound to sell, and to move out by the completion date.\n\nPlease reply to confirm that you are happy to go ahead and that we have your authority to exchange contracts{{completionLine}}.\n\n{{feeEarner}}\n{{firmName}}'),
  ownership_basis_request__transfer: T('ownership_basis_request__transfer', 'client', 'Your transfer of equity of {{property}}: how you will own it', 'Hello {{firstName}},\n\nAfter the transfer you will own {{property}} together, and we need to know how:\n\n• Joint tenants: you own the whole property together. If one of you dies, the other automatically owns it all, whatever a will says.\n• Tenants in common: you each own a share (equal or unequal), which passes under your will, recorded in a declaration of trust.\n\nPlease reply to tell us which you choose (and the shares, for tenants in common). Each of you can speak to us separately before deciding.\n\n{{feeEarner}}\n{{firmName}}'),
  balance_request__remortgage: T('balance_request__remortgage', 'client', 'Your remortgage of {{property}}: funds for completion', 'Hello {{firstName}},\n\nYour remortgage of {{property}} completes on {{completionDate}}. The completion statement we sent shows a shortfall between the new advance and what is needed to pay off your current mortgage and costs; please make sure that amount reaches our client account as cleared funds at least two working days before completion.\n\nWe will give you our bank details by phone. Never send money to bank details you receive by email, even if the email appears to come from us: always check them with us by phone first.\n\n{{feeEarner}}\n{{firmName}}'),
  deposit_request: T('deposit_request', 'client', 'Your purchase of {{property}}: the deposit', 'Hello {{firstName}},\n\nThe contract for {{property}} is approved. Before we can exchange we need your deposit{{depositAmount}} in our client account as cleared funds.\n\nWe will give you our bank details by phone. Never send money to bank details you receive by email, even if the email appears to come from us: always check them with us by phone first.\n\n{{feeEarner}}\n{{firmName}}'),
  completion_statement: T('completion_statement', 'client', 'Your {{transaction}} of {{property}}: completion statement', 'Hello {{firstName}},\n\nPlease find attached the completion statement for {{property}}, setting out the money due on completion. Please check it and let us know straight away if anything looks wrong; we will confirm the final figure and the date it must reach us.\n\nNever send money to bank details you receive by email, even if the email appears to come from us: always check them with us by phone first.\n\n{{feeEarner}}\n{{firmName}}'),
  id_check_request: T('id_check_request', 'client', 'Your {{transaction}} of {{property}} — confirming your identity', 'Hello {{firstName}},\n\nBefore we go any further on {{property}} we need to confirm your identity. The law requires this of everyone we act for (the money laundering regulations); it is not a reflection on you.\n\n{{idLinkLine}}\n\nIt takes a few minutes: have your passport or driving licence to hand.\n\n{{feeEarner}}\n{{firmName}}'),
  proof_of_funds_request: T('proof_of_funds_request', 'client', 'Your purchase of {{property}} — proof of funds', 'Hello {{firstName}},\n\nBefore we can exchange contracts on {{property}} we must verify where the money for the purchase is coming from — this is a legal requirement for every purchase, not a reflection on you.\n\nPlease complete our secure proof-of-funds form: {{formUrl}}\n\nIt asks where each part of the money comes from (savings, a sale, a gift, a mortgage…) and lets you attach bank statements and other documents. It takes about ten minutes. {{noteToClient}}\n\nWe cannot exchange until this is done, so the sooner the better.\n\n{{feeEarner}}\n{{firmName}}', ['formUrl']),
  proof_of_funds_request_again: T('proof_of_funds_request_again', 'client', 'Your purchase of {{property}} — proof of funds: a little more needed', 'Hello {{firstName}},\n\nThank you for completing the proof-of-funds form for {{property}}. Your conveyancer has reviewed it and needs a little more before it can be signed off:\n\n{{noteToClient}}\n\nPlease use this link to add to your answers or attach the extra documents: {{formUrl}}\n\n{{feeEarner}}\n{{firmName}}', ['formUrl', 'noteToClient']),
  // Paired with a chase to a third party: the client hears that we are on it, without
  // having to ask. Process only — who we are waiting for and that we chased today.
  // After a stage is signed off: what we approved, where everything else stands, what happens next and when. The line that stops the client ringing.
  progress_update: T('progress_update', 'client', 'Your {{transaction}} of {{property}} — {{done}}', 'Hello {{firstName}},\n\n{{doneLine}}\n\n{{nextStep}}\n\n{{feeEarner}}\n{{firmName}}'),
  survey_advice: T('survey_advice', 'client', 'Your {{transaction}} of {{property}} — your survey', 'Hello {{firstName}},\n\n{{adviceBody}}\n\n{{feeEarner}}\n{{firmName}}', ['property', 'adviceBody']),
  request_survey_report: T('request_survey_report', 'client', 'Your {{transaction}} of {{property}} — your survey report', 'Hello {{firstName}},\n\nWe understand your survey of {{property}} has been carried out. The surveyor reports to you rather than to us, so could you send us a copy of the report when you have it? We read it straight away and will tell you if anything in it needs dealing with before exchange.\n\n{{feeEarner}}\n{{firmName}}', ['property']),
  mortgage_status_client: T('mortgage_status_client', 'client', 'Your {{transaction}} of {{property}} — your mortgage', 'Hello {{firstName}},\n\nYour broker or lender has told us there may be a difficulty with your mortgage offer ({{quote}}). We have asked them to confirm where the offer stands. Nothing moves towards exchange until we know, so please do not commit to dates in the meantime; if you have heard anything from them yourself, let us know.\n\n{{feeEarner}}\n{{firmName}}', ['property']),
  mortgage_change_query: T('mortgage_change_query', 'client', 'Your {{transaction}} of {{property}} — your mortgage', 'Hello {{firstName}},\n\nYou mentioned a change that may affect your mortgage ({{quote}}). Could you tell us exactly what has changed and when, and whether you have spoken to your broker or lender? A change in circumstances has to be reported to the lender before we exchange, so we would rather deal with it now than find out later.\n\n{{feeEarner}}\n{{firmName}}', ['property']),
  signing_pack: T('signing_pack', 'client', 'Your {{transaction}} of {{property}} — documents to sign', 'Hello {{firstName}},\n\n{{signingIntro}}\n\n{{wetBlock}}{{electronicBlock}}Please do not date anything; we date the documents on completion. If anything is unclear, or you cannot find an independent witness, call us before you sign.\n\n{{feeEarner}}\n{{firmName}}', ['property', 'signingIntro']),
  confirm_with_client: T('confirm_with_client', 'client', 'Your {{transaction}} of {{property}} — can you confirm?', 'Hello {{firstName}},\n\n{{saidBy}} has told us that {{claim}}. We only act on that when it comes from you, so could you reply to confirm it is right, or tell us if it is not?\n\n{{feeEarner}}\n{{firmName}}', ['saidBy', 'claim']),
  access_conditions: T('access_conditions', 'client', 'Your {{transaction}} of {{property}} — access for the specialist', 'Hello {{firstName}},\n\nThe seller\'s solicitor has come back to us about access for the {{specialist}} at {{property}}. Their reply, in short: {{conditions}}\n\nIf you are happy with that, please book the specialist and tell us the date; we will confirm it with the seller\'s side. Send us the report when you have it and we will read it and advise you.\n\n{{feeEarner}}\n{{firmName}}', ['property', 'specialist', 'conditions']),
  file_password: T('file_password', 'client', 'Password for the file we have sent you', 'Hello {{firstName}},\n\nWe have sent you {{fileName}} ({{inside}}) in a separate message. It is password-protected; the password is:\n\n{{password}}\n\nWe send the file and the password separately on purpose. If anything does not open, call us rather than replying with the password.\n\n{{feeEarner}}\n{{firmName}}', ['fileName', 'password']),
  chase_update: T('chase_update', 'client', 'Your {{transaction}} of {{property}} — we have chased today', 'Hello {{firstName}},\n\nA quick update on {{property}}: we are still waiting for {{waitingOn}} to come back to us on {{waitingFor}}. We chased them again today{{nextChaseNote}}.\n\nThere is nothing you need to do at the moment — we will let you know as soon as we hear.\n\n{{feeEarner}}\n{{firmName}}', ['property', 'waitingOn', 'waitingFor']),
  qa_routed_to_human: T('qa_routed_to_human', 'client', 'Your question', 'Thanks for your message. Because it relates to the specifics of your purchase, {{feeEarner}} will come back to you personally rather than this automated service. If it is urgent, please call the office.', ['feeEarner']),
};

export const CHASES: Record<string, Template> = {
  chase_search_provider: T('chase_search_provider', 'chase', '{{matterRef}} — {{searchName}} search outstanding ({{address}})', 'Dear Sirs,\n\nOur reference {{matterRef}}. We ordered a {{searchName}} for {{address}} on {{orderedDate}} ({{ageWorkingDays}} working days ago) and have not yet received the result{{priorChaseNote}}. Please confirm the current position and expected return date.\n\nKind regards,\n{{feeEarner}}\n{{firmName}}', ['matterRef', 'address']),
  chase_enquiry_reply: T('chase_enquiry_reply', 'chase', '{{address}} — replies to enquiries outstanding (our ref {{matterRef}})', 'Dear Sirs,\n\nOur reference {{matterRef}}. We refer to our enquiries in respect of {{address}}, which remain unanswered{{priorChaseNote}}.\n\n{{resend}}\n\nOur client is anxious to proceed; please let us have your client\'s replies by return, or tell us when to expect them.\n\nKind regards,\n{{feeEarner}}\n{{firmName}}', ['matterRef', 'address']),
  chase_proof_of_funds: T('chase_proof_of_funds', 'client', 'Your purchase of {{property}} — proof of funds still needed', 'Hello {{firstName}},\n\nA reminder that we are still waiting for your proof-of-funds form for {{property}}. We cannot exchange contracts until it is complete.\n\n{{resend}}\n\nIf anything in it is unclear, reply here and we will help.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_contract_pack: T('chase_contract_pack', 'chase', '{{address}} — draft contract pack (our ref {{matterRef}})', 'Dear Sirs,\n\nOur reference {{matterRef}}. We act for the buyer of {{address}} and are still waiting for the draft contract pack{{priorChaseNote}}.\n\n{{resend}}\n\nWe should be grateful to receive it as soon as possible, so that we can raise our enquiries and report to our client without delay.\n\nYours faithfully,\n{{firmName}}'),
  chase_management_pack: T('chase_management_pack', 'chase', '{{address}} — management pack outstanding (our ref {{matterRef}})', 'Dear Sirs,\n\nOur reference {{matterRef}}. We refer to our request for the leasehold management pack for {{address}}. It remains outstanding{{priorChaseNote}} and is holding our client\'s pre-contract enquiries.\n\n{{resend}}\n\nPlease let us have it, or confirm when the managing agent expects to release it.\n\nYours faithfully,\n{{firmName}}'),
  chase_signed_documents: T('chase_signed_documents', 'client', 'Your {{transaction}} of {{property}} — signed documents', 'Hello {{firstName}},\n\nA reminder that we still need the documents we sent you to sign for {{property}}. We cannot complete without them{{lenderLine}}.\n\n{{resend}}\n\nIf anything in them is unclear, or you cannot find an independent witness, call us.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_property_forms: T('chase_property_forms', 'client', 'Your sale of {{property}} — property forms needed', 'Hello {{firstName}},\n\nWe are still waiting for your completed property forms for {{property}}. We cannot send the contract pack to the buyer\'s solicitor until they are back, and every week of delay here is a week added to the sale.\n\n{{resend}}\n\n{{feeEarner}}\n{{firmName}}'),
  chase_redemption_statement: T('chase_redemption_statement', 'chase', '{{address}} — redemption statement outstanding (our ref {{matterRef}})', 'Dear Sirs,\n\nOur reference {{matterRef}}. We requested a redemption statement for the charge over {{address}} and have not received it{{priorChaseNote}}.\n\n{{resend}}\n\nYours faithfully,\n{{firmName}}'),
  chase_lender_consent: T('chase_lender_consent', 'chase', '{{address}} — consent to transfer outstanding (our ref {{matterRef}})', 'Dear Sirs,\n\nOur reference {{matterRef}}. We applied for your consent to the proposed transfer of equity of {{address}} and await your decision{{priorChaseNote}}. Please confirm consent, and any conditions, so the transfer can proceed.\n\nYours faithfully,\n{{firmName}}'),
  chase_discharge: T('chase_discharge', 'chase', '{{address}} — evidence of discharge outstanding (our ref {{matterRef}})', 'Dear Sirs,\n\nOur reference {{matterRef}}. The charge over {{address}} was redeemed on completion and we await the DS1 or electronic discharge{{priorChaseNote}}. Please confirm the discharge has been lodged with HM Land Registry.\n\nYours faithfully,\n{{firmName}}'),
  chase_id_documents: T('chase_id_documents', 'client', 'Your {{transaction}} of {{property}} — identity check still needed', 'Hello {{firstName}},\n\nA reminder that we still need to complete the identity check for {{property}}. It is a legal requirement for every client, and we cannot progress the matter until it is done.\n\n{{resend}}\n\n{{feeEarner}}\n{{firmName}}'),
  chase_mortgage_offer: T('chase_mortgage_offer', 'client', 'Your purchase of {{property}} — how is the mortgage going?', 'Hello {{firstName}},\n\nWe have not yet had your mortgage offer for {{property}}, and we cannot exchange contracts without it. Could you let us know where things are?\n\n• Has the application gone in, and has the lender\'s valuation been done?\n• When does your broker or lender expect to issue the offer?\n\nWhen it is issued, the lender sends us our own copy; it helps if you forward yours as well. If anything has changed (the amount, the lender, your circumstances), tell us straight away.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_survey: T('chase_survey', 'client', 'Your purchase of {{property}} — have you arranged a survey?', 'Hello {{firstName}},\n\nWe have not heard whether you are having a survey of {{property}}. {{valuationLine}}Whether to have a survey is your choice, but it is best done before we are ready to exchange, while there is still time to act on what it finds.\n\nPlease reply to let us know:\n• if you have booked one, the date, and send us the report when you have it;\n• if you have decided not to have one, so we can note it on your file.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_deposit: T('chase_deposit', 'client', 'Your purchase of {{property}}: the deposit', 'Hello {{firstName}},\n\nA reminder that we need your deposit in our client account, as cleared funds, before we can exchange contracts for {{property}}. If you have already sent it, reply to let us know when, and from which account.\n\nWe give our bank details by phone only. Never act on bank details sent by email.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_ownership_basis: T('chase_ownership_basis', 'client', 'Your purchase of {{property}}: how you will own it', 'Hello {{firstName}},\n\nA reminder that we need to know whether you will own {{property}} as joint tenants or as tenants in common (with the shares). We cannot prepare the transfer without it. Reply here, or call us if you would like to talk it through.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_exchange_authority: T('chase_exchange_authority', 'client', 'Your purchase of {{property}}: your authority to exchange', 'Hello {{firstName}},\n\nA reminder that we need your confirmation that we may exchange contracts for {{property}}. Everything else is ready on our side. Please reply to confirm, or call us with any questions first.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_buildings_insurance: T('chase_buildings_insurance', 'client', 'Your purchase of {{property}}: buildings insurance', 'Hello {{firstName}},\n\nWe still need a copy of your buildings insurance schedule for {{property}} (insurer, start date and your lender noted). Your lender will not release the mortgage money for completion without it.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_client_funds: T('chase_client_funds', 'client', 'Your purchase of {{property}}: completion funds', 'Hello {{firstName}},\n\nCompletion of {{property}} is set for {{completionDate}} and we have not yet received the balance from you. Please make sure it reaches our client account as cleared funds in time, and let us know when you have sent it.\n\nWe give our bank details by phone only. Never act on bank details sent by email.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_mortgage_offer__remortgage: T('chase_mortgage_offer__remortgage', 'client', 'Your remortgage of {{property}} — how is the new mortgage going?', 'Hello {{firstName}},\n\nWe have not yet had your new mortgage offer for {{property}}, and your remortgage cannot complete without it. Could you let us know where things are: has the lender done its valuation, and when does your broker expect the offer?\n\nThe lender sends us our own copy when it is issued. If anything has changed, tell us straight away.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_exchange_authority__sale: T('chase_exchange_authority__sale', 'client', 'Your sale of {{property}}: your authority to exchange', 'Hello {{firstName}},\n\nA reminder that we need your confirmation that we may exchange contracts on your sale of {{property}}. Please reply to confirm, or call us with any questions first.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_ownership_basis__transfer: T('chase_ownership_basis__transfer', 'client', 'Your transfer of equity of {{property}}: how you will own it', 'Hello {{firstName}},\n\nA reminder that we need to know whether you will own {{property}} as joint tenants or as tenants in common (with the shares). We cannot prepare the transfer without it.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_client_funds__remortgage: T('chase_client_funds__remortgage', 'client', 'Your remortgage of {{property}}: completion funds', 'Hello {{firstName}},\n\nYour remortgage of {{property}} completes on {{completionDate}} and we have not yet received the funds from you shown on the completion statement. Please make sure they reach our client account in time, and let us know when you have sent them.\n\nWe give our bank details by phone only. Never act on bank details sent by email.\n\n{{feeEarner}}\n{{firmName}}'),
  chase_completion_funds: T('chase_completion_funds', 'chase', '{{matterRef}} — completion funds ({{address}})', 'Dear Sirs,\n\nOur reference {{matterRef}}. Completion of {{address}} is scheduled for {{completionDate}}. We requested the advance/completion monies on {{orderedDate}} and have not yet received confirmation of release. Please confirm the funds will arrive in time.\n\nKind regards,\n{{feeEarner}}\n{{firmName}}', ['matterRef', 'address']),
  chase_hmlr_registration: T('chase_hmlr_registration', 'chase', '{{matterRef}} — AP1 registration outstanding ({{address}})', 'Dear Sirs,\n\nOur reference {{matterRef}}. Our AP1 application for {{address}} was lodged on {{orderedDate}} and remains outstanding after {{ageWorkingDays}} working days. Please confirm the current position.\n\nKind regards,\n{{feeEarner}}\n{{firmName}}', ['matterRef', 'address']),
};


/** Notices to other parties on the matter: news, not a chase. */
export const PARTY_NOTICES: Record<string, Template> = {
  request_contract_pack: T('request_contract_pack', 'chase', '{{address}}: draft contract pack (our ref {{matterRef}})', 'Dear {{recipientName}},\n\nWe act for the buyer of {{address}}. Please send us the draft contract pack: the draft contract, official copies of the register and title plan, the Property Information Form (TA6) and the Fittings and Contents Form (TA10){{leaseholdForms}}, and copies of any planning permissions, building regulations certificates and guarantees your client holds.\n\nWe look forward to hearing from you.\n\n{{feeEarner}}\n{{firmName}}'),
  request_management_pack: T('request_management_pack', 'chase', '{{address}}: leasehold management pack (our ref {{matterRef}})', 'Dear {{recipientName}},\n\nWe act for the buyer of {{address}}. Please obtain from the landlord or managing agent the leasehold information pack (LPE1), with the service charge accounts for the last three years, the current budget, the buildings insurance schedule and any notice of planned major works, and send it to us with the contract papers.\n\n{{feeEarner}}\n{{firmName}}'),
  request_redemption_statement: T('request_redemption_statement', 'chase', '{{address}}: redemption statement (our ref {{matterRef}})', 'Dear {{recipientName}},\n\nWe act for your borrower on the sale of {{address}}. Please send us a redemption statement for the mortgage secured on the property, to {{completionDate}}, showing the daily rate of interest after that date. If you need your borrower\'s signed authority, please let us know and we will send it.\n\n{{feeEarner}}\n{{firmName}}'),
  request_redemption_statement__remortgage: T('request_redemption_statement__remortgage', 'chase', '{{address}}: redemption statement (our ref {{matterRef}})', 'Dear {{recipientName}},\n\nWe act for your borrower, who is remortgaging {{address}} to another lender. Please send us a redemption statement for the mortgage secured on the property, to {{completionDate}}, showing the daily rate of interest after that date. If you need your borrower\'s signed authority, please let us know and we will send it.\n\n{{feeEarner}}\n{{firmName}}'),
  request_lender_consent: T('request_lender_consent', 'chase', '{{address}}: your consent (our ref {{matterRef}})', 'Dear {{recipientName}},\n\nWe act for your borrower in a transaction affecting {{address}}, which is charged to you. Please confirm your consent to it, and let us know any conditions or documents you require.\n\n{{feeEarner}}\n{{firmName}}'),
  request_discharge: T('request_discharge', 'chase', '{{address}}: discharge of your charge (our ref {{matterRef}})', 'Dear {{recipientName}},\n\nWe act for your borrower. The mortgage secured on {{address}} was redeemed on completion today with the sum in your redemption statement. Please lodge the discharge with HM Land Registry (e-DS1), or send us a sealed DS1, and confirm the account is closed.\n\n{{feeEarner}}\n{{firmName}}'),
  exchanged_agent: T('exchanged_agent', 'chase', '{{address}}: contracts exchanged (our ref {{matterRef}})', 'Dear {{recipientName}},\n\nContracts for {{address}} have been exchanged today. Completion is set for {{completionDate}}.\n\n{{feeEarner}}\n{{firmName}}'),
  completed_agent: T('completed_agent', 'chase', '{{address}}: completed (our ref {{matterRef}})', 'Dear {{recipientName}},\n\nCompletion of {{address}} has taken place today, and the keys may be released.\n\n{{feeEarner}}\n{{firmName}}'),
  enquiries_to_seller_solicitor: T('enquiries_to_seller_solicitor', 'chase', '{{address}}: enquiries (our ref {{matterRef}})', 'Dear {{solicitorName}},\n\nWe act for the buyer of {{address}}. Please let us have your replies to the following enquiries.\n\n{{enquiries}}\n\nWe look forward to hearing from you.\n\n{{feeEarner}}\n{{firmName}}'),
  confirm_offer_status: T('confirm_offer_status', 'chase', '{{address}} — mortgage offer, our ref {{matterRef}}', 'Dear {{agentName}},\n\nWe act for the buyer of {{address}}. We understand from you that there may be a difficulty with the mortgage offer ("{{quote}}"). Please confirm by return whether the offer stands and, if not, what is required and on what timetable, so that we can advise our client before exchange.\n\nKind regards,\n{{feeEarner}}\n{{firmName}}', ['matterRef', 'address']),
  chase_update_agent: T('chase_update_agent', 'chase', '{{address}} — chased today (our ref {{matterRef}})', 'Dear {{agentName}},\n\nA quick update on {{address}}: we are waiting for {{waitingOn}} to come back to us on {{waitingFor}}. We chased them again today{{nextChaseNote}}.\n\nNothing is needed from you at the moment — we will let you know as soon as we hear.\n\nKind regards,\n{{feeEarner}}\n{{firmName}}', ['address', 'waitingOn', 'waitingFor']),
};

/** Acknowledgements: it arrived, it is with us, no need to chase. */
export const ACKS: Record<string, Template> = {
  ack_counterparty: T('ack_counterparty', 'chase', '{{address}} — received, thank you (our ref {{matterRef}})', 'Dear Sirs,\n\nThank you — we have received {{what}} in respect of {{address}}. It is with {{feeEarner}} for review and we will revert if anything further is needed.\n\nKind regards,\n{{feeEarner}}\n{{firmName}}', ['matterRef', 'address', 'what']),
  ack_client: T('ack_client', 'client', '{{property}} — received, thank you', 'Hello {{firstName}},\n\nThank you — we have received {{what}} for {{property}}. {{feeEarner}} will review it and we will be in touch if anything is needed. Nothing more is needed from you right now.\n\n{{feeEarner}}\n{{firmName}}', ['property', 'what']),
};

export const SEARCH_NAMES: Record<string, string> = {
  LLC1: 'local land charges search (LLC1)',
  CON29: 'local authority search (CON29)',
  DRAINAGE_WATER: 'drainage and water search',
  ENVIRONMENTAL: 'environmental search',
  CHANCEL: 'chancel repair search',
};

export interface Rendered {
  subject: string;
  body: string;
  missing: string[];
}

export function render(t: Template, vars: Record<string, string | number | null | undefined>): Rendered {
  const missing: string[] = [];
  const sub = (s: string) =>
    s.replace(/\{\{(\w+)\}\}/g, (_, k: string) => {
      const v = vars[k];
      if (v === null || v === undefined || v === '') {
        if (t.requires.includes(k) && !missing.includes(k)) missing.push(k);
        return '';
      }
      return String(v);
    });
  return { subject: sub(t.subject).replace(/\s{2,}/g, ' ').trim(), body: sub(t.body).replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim(), missing };
}

/** The template for this kind of case: `key__sale`, `key__remortgage` or `key__transfer` where the words differ, else the default. */
export function forTransaction(reg: Record<string, Template>, key: string, transaction?: string | null): Template | undefined {
  return (transaction && reg[`${key}__${transaction}`]) || reg[key];
}

export function templateFor(key: string): Template | null {
  return CLIENT_UPDATES[key] ?? CHASES[key] ?? null;
}


/**
 * Why a rendered message must not be sent, or null. The last line of defence between a bad
 * reading or a missing value and someone's inbox: a message that fails goes to a person as a
 * task with the reason, never out. Deliberately blunt: a false alarm costs a click, a false pass
 * costs the firm's credibility.
 */
export function messageProblem(r: { subject: string; body: string; missing?: string[] }): string | null {
  if (r.missing?.length) return `it is missing ${r.missing.join(', ')}`;
  const text = `${r.subject}\n${r.body}`;
  const checks: Array<[RegExp, string]> = [
    [/\{\{|\}\}/, 'a placeholder was not filled in'],
    [/\bundefined\b|\bNaN\b|\[object Object\]/, 'a value is missing (it reads "undefined")'],
    [/(^|[\s:(])null([\s.,)]|$)/m, 'a value is missing (it reads "null")'],
    [/could not be read automatically|a person must read it|\bUNREAD\b/i, 'it quotes a document the system could not read'],
    [/£0(\.00)?\b/, 'it states an amount of £0'],
    [/\b(Tenant|MATTER)-[0-9a-f-]{8,}/i, 'it contains an internal reference'],
    [/(^|\n)\s*•\s*(\n|$)/, 'it has an empty bullet'],
  ];
  for (const [re, why] of checks) if (re.test(text)) return why;
  // A heading ("Where everything else stands:") with nothing under it: a section whose content never arrived.
  const lines = r.body.split('\n').map((l) => l.trim());
  for (let i = 0; i < lines.length; i++) {
    if (!/^[A-Z][^.!?]{2,60}:$/.test(lines[i])) continue;
    const next = lines.slice(i + 1).find((l) => l.length > 0);
    if (!next || /^[A-Z][^.!?]{2,60}:$/.test(next)) return `the section "${lines[i].slice(0, -1)}" is empty`;
  }
  if (r.body.trim().length < 40) return 'it is almost empty';
  return null;
}
