/**
 * The seller's property information forms (TA6, TA7 for a leasehold, TA10 fittings and contents)
 * read into typed answers, and the deterministic rules that turn an answer into an issue on the
 * file. On a purchase the forms arrive with the contract pack and the rules protect the buyer;
 * on a sale they are our client's answers and the same rules say what must be disclosed properly
 * before the pack goes out (the Protocol: the seller answers the TA6 in full and truthfully).
 *
 * Facts, not judgements: each rule cites the answer verbatim and names the issue kind; the
 * conveyancer decides what to do with it. Nothing here drafts advice.
 */
import type { Flag, PropertyFormsFacts } from './types';
import type { IssueKind } from './issues';

export interface FormsIssue { kind: IssueKind; title: string; detail: string; page: number | null; flag: Flag }

const yes = (v: boolean | null | undefined): boolean => v === true;
/** Shortened on a word, never mid-word. */
const clip = (s: string, n: number): string => { const t = s.replace(/\s+/g, ' ').trim(); if (t.length <= n) return t; const cut = t.slice(0, n); return `${cut.slice(0, Math.max(cut.lastIndexOf(' '), n - 20)).replace(/[,;:.\s]+$/, '')}…`; };
/** A remark about the document itself (which forms it holds or lacks) is not something the seller disclosed. */
const aboutTheDocument = (s: string): boolean => /\b(this|the) (document|file|pdf|form)\b.*\b(only|does not|doesn't|contains no|is not|lacks|missing)\b|\bdoes not contain\b|\bonly (a|the) TA ?\d+\b|\bnot (included|present) in this (document|file)\b/i.test(s);
const some = (v: string | null | undefined): v is string => !!v && v.trim().length > 0 && !/^(none|no|n\/a|not applicable|not known|nil)\.?$/i.test(v.trim());

/** Deterministic rules over the TA6 / TA7 answers. `side` says whose forms they are. */
export function propertyFormsIssues(f: PropertyFormsFacts, side: 'buyer' | 'seller', opts: { buyToLet?: boolean } = {}): FormsIssue[] {
  const out: FormsIssue[] = [];
  const who = side === 'buyer' ? 'The seller' : 'Our client';
  const push = (kind: IssueKind, code: string, title: string, detail: string, page: number | null, severity: Flag['severity'] = 'medium') => out.push({ kind, title, detail, page, flag: { code, severity, description: title, locator: page != null ? { page } : undefined } });
  const a = f.answers ?? {};
  if (some(a.disputes)) push('disclosure_concern', 'TA6_DISPUTE', `TA6: a dispute or complaint is disclosed — "${a.disputes!.slice(0, 160)}"`, `${who} discloses a dispute, complaint or notice with a neighbour or third party (TA6 section 2). Raise an enquiry for the full history and any correspondence; consider whether it affects value or the lender; the buyer must be told before exchange.`, f.pages?.disputes ?? null, 'high');
  if (some(a.notices)) push('disclosure_concern', 'TA6_NOTICE', `TA6: a notice or proposal affecting the property — "${a.notices!.slice(0, 160)}"`, `${who} discloses a notice, planning proposal or letter affecting the property or a neighbour (TA6 section 3). Obtain the notice and check the local search against it.`, f.pages?.notices ?? null);
  if (some(a.alterations) && !yes(a.alterationsConsented)) push('building_regs_missing', 'TA6_ALTERATIONS_NO_CONSENT', `TA6: works carried out without the consents listed — "${a.alterations!.slice(0, 160)}"`, `${who} lists building works, extensions, conversions or replacement windows (TA6 section 4) and does not say every planning permission, building regulations approval or completion certificate is held. Ask for the paperwork; an indemnity policy is the usual fallback for old works, regularisation for recent ones; the lender must be told of any breach.`, f.pages?.alterations ?? null, 'high');
  if (some(a.alterations) && yes(a.alterationsConsented) && !yes(a.alterationsDocumentsEnclosed)) push('document_missing', 'TA6_ALTERATIONS_DOCS', `TA6: consents for the works are said to exist but are not enclosed`, `${who} says the works (${a.alterations!.slice(0, 120)}) had the consents required but the planning permissions, building regulations certificates or FENSA / Gas Safe certificates are not with the forms. Ask for them; the buyer's lender needs them.`, f.pages?.alterations ?? null, 'low');
  if (some(a.guaranteesOutstandingClaims)) push('disclosure_concern', 'TA6_GUARANTEE_CLAIM', `TA6: an outstanding claim under a guarantee — "${a.guaranteesOutstandingClaims!.slice(0, 160)}"`, `A claim under a guarantee (damp, timber, roofing, windows, NHBC) is in progress or was refused (TA6 section 5). Establish what the defect is and whether it is remedied.`, f.pages?.guarantees ?? null);
  if (some(a.insuranceClaims) || yes(a.insuranceRefused)) push('disclosure_concern', 'TA6_INSURANCE', `TA6: insurance claims or cover refused — "${(a.insuranceClaims ?? 'cover refused or on special terms').slice(0, 160)}"`, `${who} discloses buildings insurance claims, refused cover or special terms (TA6 section 6). Subsidence, flood and fire history goes to insurability and the lender.`, f.pages?.insurance ?? null, 'high');
  if (yes(a.flooded)) push('environmental_risk', 'TA6_FLOODED', `TA6: the property has flooded${some(a.floodDetail) ? ` — "${a.floodDetail!.slice(0, 140)}"` : ''}`, `${who} says the property or its land has flooded (TA6 section 7). Match against the environmental search, ask when, how often and what was done, and check that insurance is obtainable on normal terms; the lender will want that confirmed.`, f.pages?.environment ?? null, 'high');
  if (yes(a.japaneseKnotweed)) push('environmental_risk', 'TA6_KNOTWEED', `TA6: Japanese knotweed is present or was treated${some(a.knotweedDetail) ? ` — "${a.knotweedDetail!.slice(0, 140)}"` : ''}`, `${who} answers "yes" to Japanese knotweed (TA6 section 7). Ask for the management plan and the specialist's insurance-backed guarantee; most lenders lend only with a treatment plan in place.`, f.pages?.environment ?? null, 'high');
  if (yes(a.radonTestAboveAction)) push('environmental_risk', 'TA6_RADON', 'TA6: a radon test was above the action level', `${who} says a radon test was carried out and the result was at or above the action level, or remedial works were done (TA6 section 7). Confirm the remedial measures and re-test results.`, f.pages?.environment ?? null);
  if (some(a.occupiers)) push('occupier_consent', 'TA6_OCCUPIERS', `TA6: occupiers other than the seller — ${a.occupiers!.slice(0, 120)}`, side === 'buyer' ? 'Adults living at the property who are not the seller (TA6 section 11) must vacate on completion; the contract should require vacant possession and the seller\'s solicitor should confirm they will go. On our client\'s side of a purchase the lender needs any occupier of ours to sign a consent.' : `Adults living at the property who are not our client (TA6 section 11): each must agree to leave on completion, and the contract must be able to promise vacant possession. Get their signed confirmation before exchange.`, f.pages?.occupiers ?? null);
  if (yes(a.sharedAccessOrServices) || some(a.rightsOfWayOverProperty)) push('missing_easement', 'TA6_RIGHTS', `TA6: shared access, services or rights over the property — "${(a.rightsOfWayOverProperty ?? 'shared access or services').slice(0, 140)}"`, `${who} discloses shared drives, paths or services, or rights others have over the property (TA6 sections 8 and 9). Check the title grants and reserves them; a missing easement is a title defect the lender will want covered.`, f.pages?.rights ?? null);
  if (yes(a.septicTank)) push('third_party_encumbrance', 'TA6_SEPTIC', 'TA6: private drainage (septic tank or treatment plant)', `The property drains to a septic tank or treatment plant (TA6 section 12). Since 2020 a septic tank discharging to a watercourse must have been replaced or upgraded; ask for the installation details, the last emptying and any permit. Not connected to the mains is also a lender question.`, f.pages?.services ?? null);
  if (yes(a.solarPanelsLeased)) push('third_party_encumbrance', 'TA6_SOLAR_LEASE', 'TA6: solar panels under a lease or a third-party agreement', `The roof is let or the panels belong to a third party (TA6 section 12). The lender needs the lease to meet the UK Finance / lender requirements (the standard "solar panel" conditions) and the lease is a title encumbrance.`, f.pages?.services ?? null);
  if (some(a.boundariesUnclear)) push('boundary_discrepancy', 'TA6_BOUNDARIES', `TA6: boundary answer needs checking — "${a.boundariesUnclear!.slice(0, 140)}"`, `${who} is unsure who owns or maintains a boundary, or a boundary has moved (TA6 section 1). Compare with the title plan and raise an enquiry.`, f.pages?.boundaries ?? null, 'low');
  if (yes(a.listedOrConservation)) push('planning_permission_missing', 'TA6_LISTED', 'TA6: listed building or conservation area', `The property is listed or in a conservation area (TA6 section 4). Works need listed building consent; check every alteration disclosed against it, and tell the lender.`, f.pages?.alterations ?? null, 'low');
  if (yes(a.leaseholdArrearsOrDispute)) push('service_charge_issue', 'TA7_ARREARS', 'TA7: service charge or ground rent arrears, or a dispute with the landlord', `${who} discloses arrears or a dispute under the lease (TA7). Match against the management pack; arrears are settled on completion or retained.`, f.pages?.leasehold ?? null);
  // Works without consent, dated (property.md 3.1): in England a breach since 25 April 2024 is immune after 10 years; operational development finished before then, after 4.
  if (some(a.alterations) && !yes(a.alterationsConsented) && some(a.alterationsYear) && /^\d{4}$/.test(a.alterationsYear!.trim())) {
    const y = Number(a.alterationsYear!.trim()); const now = new Date().getUTCFullYear();
    const immune = y < 2024 ? now - y >= 4 : now - y >= 10;
    push('planning_permission_missing', 'TA6_PLANNING_DATED', `Works done in ${y} without the consents: ${immune ? 'past the enforcement period' : 'still inside the enforcement period'}`, immune ? `Planning enforcement is time-barred for works done in ${y} (4 years for building works finished before 25 April 2024, 10 years since). Building regulations enforcement has its own limit (12 months for a prosecution, longer for an injunction): an indemnity policy covers it. Do not approach the council first: that voids the indemnity.` : `Works done in ${y} can still be enforced against (England: 10 years for breaches since 25 April 2024). Options: a retrospective application by the seller, or an indemnity policy (never contact the council first: that voids the policy). Tell the lender.`, null, immune ? 'medium' : 'high');
  }
  if (yes(a.windowsReplacedSince2002) && !yes(a.windowsCertificate)) push('building_regs_missing', 'TA6_WINDOWS', 'TA6: windows replaced since April 2002 with no FENSA / CERTASS certificate', 'Replacement windows and glazed doors since 1 April 2002 need building regulations approval, shown by a FENSA or CERTASS certificate or the council\'s record. Ask for it; failing that, an indemnity policy is usual.', null);
  if (yes(a.electricalWorkSince2005) && !yes(a.electricalCertificate)) push('building_regs_missing', 'TA6_ELECTRICS', 'TA6: electrical work since 2005 with no Part P certificate', 'Notifiable electrical work since January 2005 needs a Part P certificate (an NICEIC or similar installer\'s, or the council\'s). Ask for it; otherwise the client can commission an electrical installation condition report (EICR). Record their choice.', null);
  if (yes(a.gasApplianceNoRecord)) push('building_regs_missing', 'TA6_GAS', 'TA6: a gas appliance with no Gas Safe record', 'A boiler or gas appliance should have a Gas Safe registration record and a building regulations certificate. Ask for them; otherwise the client can have a gas safety check done. Record their choice.', null);
  if (some(a.knotweedCategory) && /^[AB]$/i.test(a.knotweedCategory!.trim())) push('environmental_risk', 'KNOTWEED_AB', `Japanese knotweed, category ${a.knotweedCategory!.trim().toUpperCase()}`, 'Category A or B (within 3 metres, or causing damage): the lender needs a specialist management plan with an insurance-backed guarantee that passes to the buyer, and may make a retention. Get the plan and the guarantee before exchange.', null, 'high');
  if (yes(a.solarPanelsOwned)) push('document_missing', 'TA6_SOLAR_OWNED', 'TA6: solar panels owned by the seller', 'Ask for the MCS certificate, the installer\'s warranty and building regulations sign-off, and for the feed-in tariff or Smart Export Guarantee to be transferred to the buyer.', null, 'low');
  if (yes(a.privateWater)) push('environmental_risk', 'TA6_PRIVATE_WATER', 'TA6: a private water supply', 'Water comes from a well, borehole or spring: get a recent water quality test and the council\'s risk assessment, an easement where the supply crosses someone else\'s land, and tell the lender.', null);
  // Energy performance: a seller must have commissioned an EPC before marketing; F or G cannot be let (MEES), which matters to a buy-to-let buyer and their lender.
  if (side === 'seller' && !some(a.epcRating)) push('document_missing', 'TA6_EPC_MISSING', 'EPC: no energy performance certificate stated on the forms', 'The seller must have commissioned an EPC before marketing (Energy Performance of Buildings Regulations 2012) and the buyer\'s solicitor will ask for it with the pack. Check the EPC register and put the certificate in the pack; if the property is to be let, a rating of F or G bars a new tenancy (MEES).', null, 'low');
  if (side === 'buyer' && some(a.epcRating) && /^[FG]$/i.test(a.epcRating!.trim()) && opts.buyToLet) push('buy_to_let_conditions', 'TA6_EPC_MEES', `EPC rating ${a.epcRating!.trim().toUpperCase()}: the property cannot be let without improvement (MEES)`, 'A domestic property rated F or G cannot be let under the Minimum Energy Efficiency Standards unless an exemption is registered; the buy-to-let lender will not accept the rental cover until it is improved to E or better. Advise the client on the cost and tell the lender.', null, 'high');
  const form = f.forms?.find((x) => x !== 'TA10' && x !== 'OTHER') ?? f.forms?.[0] ?? 'Forms';
  for (const fl of f.disclosures ?? []) if (!aboutTheDocument(fl.description) && !out.some((x) => x.flag.code === fl.code)) push('disclosure_concern', fl.code, `${form === 'OTHER' ? 'Forms' : form}: ${clip(fl.description, 110)}`, fl.description, fl.locator?.page ?? null, fl.severity);
  return out;
}
